### PR TITLE
Added admin user edition form

### PR DESCRIPTION
**Pull request by naps62**
Added a simple action and form for admins to edit user info

### CODE REVIEW

**Comment by zamith** [comment]
It would be nice if you could add some tests. ;)

**Comment by regedor** [comment]
Definitely, this a core base engine for any rails app using it.
The rest of the apps will depend on the functionalities provided by this.

It needs to be truly reliable. At least, it needs total coverage :p

**Comment by naps62** [comment]
Fixed based on comments.
That div was not suposed to be there, i agree. Don't even know why i put it in the first place

**Comment by zamith** [comment]
I have merged this, but please be careful with the whitespaces the next. Notice that "\ No newline at end of file" in the end of some files.

**Pull request closed without merging**
